export const expertiseAreas = [
  "History",
  "Philosophy",
  "Religious Studies",
  "Linguistics",
  "Literature",
  "Cultural Studies",
  "Curriculum Studies",
  "Educational Administration",
  "Educational Technology",
  "Guidance and Counselling",
  "Special Education",
  "Measurement and Evaluation",
  "Sociology",
  "Political Science",
  "Economics",
  "Psychology",
  "International Relations",
  "Public Administration",
  "Constitutional Law",
  "Criminal Law",
  "International Law",
  "Commercial Law",
  "Environmental Law",
  "Human Rights Law",
  "Islamic Law",

];