export const teams = [
  {
    category: "Editorial Board",
    description:
      "The BFC Executive Team is comprised of seasoned executives hailing from diverse asset management, entrepreneurship, and finance backgrounds.",
    members: [
      { name: "Dr. Umar Ali", role: "Editor-in-Chief", img: "/eric.jpg" },
      {
        name: "Prof. Nasir Faruk",
        role: "Managing Editor",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-zz569d-WhatsApp_Image_2025-08-22_at_00.36.00.jpeg",
      },
      {
        name: "Dr. Salisu Garba",
        role: "Asst Managing Editor",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-nk6ilf-WhatsApp_Image_2025-08-22_at_00.31.19.jpeg",
      },
      {
        name: "Prof. Rashid Husain",
        role: "Production Editor",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-zwdsz8-WhatsApp_Image_2025-08-22_at_00.33.52.jpeg",
      },
      {
        name: "Dr. Sani Durumin Iya",
        role: "Production Manager",
        img: "/erik.jpg",
      },
      {
        name: "Dr. Shuaibu Yusuf",
        role: "Editorial Secretary",
        img: "/erik.jpg",
      },
      {
        name: "Mr. Abdullahi Mikailu",
        role: "Bussiness Manager",
        img: "/mike.jpg",
      },
      {
        name: "Dr. Muhammad Jamil Ibrahim",
        role: "Asst. Production Editor",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-xx3dvl-WhatsApp_Image_2025-08-22_at_00.32.59.jpeg",
      },

      {
        name: "Ibrahim Muhammad",
        role: "Web Manager",
        img: "https://shadaijournal.com/assets/2025-08-22/image/image-20250822-9nbvvc-ibrex29.jpeg",
      },
      {
        name: "Mohammed Bala Nasir",
        role: "Web Manager",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-ooybdp-nasir-mohammed-bala.png",
      },
    ],
  },
  {
    category: "Section Editor Board",
    description:
      "The BFC Executive Team is comprised of seasoned executives hailing from diverse asset management, entrepreneurship, and finance backgrounds.",
    members: [
      {
        name: "Dr Abdullahi Haruna Birniwa",
        role: "Department of Chemistry",
        img: "http://shadaijournal.com/assets/2025-08-22/image/image-20250822-bnuutq-WhatsApp_Image_2025-08-22_at_00.37.59.jpeg",
        email: "ahbirniwa@shadaijournal.com",
        tel_number: "+234 806 549 6007",
      },
      {
        name: "Dr. Ismail Auwal Alhassan",
        role: "Department of Chemistry",
        img: "/erik.jpg",
        email: "sahiburrahmah@gmail.com",
        tel_number: "+234 803 247 2499",
      },
      {
        name: "Shamsu Ado ZAKARI (PhD)",
        role: "Soil Science Department",
        img: "/erik.jpg",
        email: "shamsuado@shadaijournal.com",
        tel_number: "+234 803 426 5669,",
      },
      {
        name: "Dr Bello Muhammad Shehu",
        role: "Department of Chemistry",
        img: "/mike.jpg",
        email: " bmshehu.ssc@buk.edu.ng",
        tel_number: "+234 803 2165 559",
      },
      {
        name: "Dr. Mustapha Sunusi",
        role: "Department of Crop Science",
        img: "/erik.jpg",
        email: "musunusi@fud.edu.ng",
        tel_number: "+234 806 742 8472",
      },
      {
        name: "Dr. Balarabe Bilyaminu Ismail",
        role: "Dept of Food and Nutrition Science",
        img: "/erik.jpg",
        email: "bbismail@zju.edu.cn",
        tel_number: "+234 -----------",
      },
      {
        name: "Dr. Nafiu Bala Sanda",
        role: "Dept of Crop Protection",
        img: "/mike.jpg",
        email: "nbsanda.crp@buk.edu.ng",
        tel_number: "+234 803 409 4770",
      },
      {
        name: "Dr Aminu Muhammad",
        role: "Dept. of Physics",
        img: "/erik.jpg",
        email: "aminu.muhammad@shadaijournal.com",
        tel_number: "+234 813 066 1127",
      },
      {
        name: "Ibrahim Garba Shitu",
        role: "Dept. of Physics",
        img: "/mike.jpg",
        email: "ibrahim.garbashitu@shadaijournal.com",
        tel_number: "+234 803 075 2731",
      },
      {
        name: "Dr Suleiman Bashir Adamu",
        role: "Dept. of Physics",
        img: "/mike.jpg",
        email: "suleimanadamubashir@shadaijournal.com",
        tel_number: "+234 703 061 5953",
      },
      {
        name: "Dr Aminu Muhammad",
        role: "Dept. of Physics",
        img: "/erik.jpg",
        email: "aminu.muhammad@shadaijournal.com",
        tel_number: "+234 813 066 1127",
      },
      {
        name: "Ibrahim Garba Shitu",
        role: "Dept. of Physics",
        img: "/mike.jpg",
        email: "ibrahim.garbashitu@shadaijournal.com",
        tel_number: "+234 803 075 2731",
      },
      {
        name: "Dr Suleiman Bashir Adamu",
        role: "Dept. of Physics",
        img: "/mike.jpg",
        email: "suleimanadamubashir@shadaijournal.com",
        tel_number: "+234 703 061 5953",
      },
      {
        name: "Dr. Idris Ahmed",
        role: "Dept. of Mathematics",
        img: "/erik.jpg",
        email: "idris.ahmed@shadaijournal.com",
        tel_number: "+234 806 193 9693",
      },
      {
        name: "Dr. Mujahid Abdullahi",
        role: "Dept. of Physics",
        img: "/mike.jpg",
        email: "mujahid.abdullahi@shadaijournal.com",
        tel_number: "+234 705 288 0419",
      },
      {
        name: "Dr. Osazee Eghosa",
        role: "Dept. of Biology",
        img: "/mike.jpg",
        email: " hope99374@gmail.com",
        tel_number: "+234 905 166 8616",
      },
    ],
  },
  {
    category: "Advisory Board",
    description:
      "The Advisory Board consists of industry leaders providing strategic guidance and expertise to the organization.",
    members: [
      "Prof. Lawan Sani Taura, SHADAI, Jigawa State Nigeria",
      "Prof. Dalha Wada Taura, Bayero University, Kano, Nigeria",
      "Prof R. G Jimoh, University of Ilorin, Ilorin, Nigeria",
      "Prof. Lawan Danlarai Fagwalawa, KUST, Wudil, Nigeria",
      "Prof. Lesley Smith. Hull University, UK",
      "Prof. Chifu E. Ndikilar, Federal University Dutse, Nigeria.",
      "Prof. Sunusi Muhammad, UDUS, Nigeria",
      "Prof. Muhammad Bashir Ibrahim, Bayero University Kano, Nigeria",
      "Prof Babawuro Usman, Kano University of Science and Technology, Wudil, Nigeria",
      "Dr A. D. Usman, Ahmadu Bello University, Zaria, Nigeria",
      "Prof. Abrar Ahmad Khan, Aligrah Muslim University, India",
      "Prof. Ahmed Baita Garko, Federal University Dutse, Nigeria",
      "Prof. Anene Moneke, UNN, Nigeria",
      "Dr. Muhamad Zaky Bin Noh, University Tun Hussein Onn Malaysia",
      "Dr Maitama Yusuf Abubakar, KUST Wudil, Kano Nigeria",
      "Prof. A. H. Arzai, Bayero University, Kano, Nigeria",
      "Prof. Fagade Oba, University of Ibadan, Nigeria",
      "Prof. Vincent Ebakwe, Federal University of Technology, Owerri, Nigeria",
      "Prof. Ekuobase Osaretin Godspower, UNIBEN, Nigeria",
      "Dr Abubakar Abdulkarim, ABU, Zaria",
      "Dr. A.O Oloyede, University of Ilorin, Nigeria",
      "Dr. Shafi’i Muhammad Abdulhamid, Federal University of Technology Minna, Nigeria.",
      "Dr. Sanusi Alhaji Jibrin, Department of Statistics, KUST Wudil, Nigeria.",
    ],
  },
];
